server {
    # 1. 80번 포트로 들어오는 모든 요청을 듣습니다.
    listen 80;
    server_name localhost;

    # 2. 모든 경로(/)에 대한 요청을 처리합니다.
    location / {
        # 핵심: 80번으로 들어온 요청을 'web'이라는 이름의 컨테이너 5000번으로 보냅니다.
        # (수동 배포때 썼던 127.0.0.1 대신 도커 서비스 이름을 씁니다)
        proxy_pass http://127.0.0.1:5000;

        # 3. 원본 요청의 정보를 전달하기 위한 헤더 설정
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # (선택 사항) 에러 페이지 설정
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}